application: flux-plant
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler: Must be /_ah/spi. Apps send requests to /_ah/api, but these are handled at /_ah/spi!!

- url: /_ah/spi/.*
  script: fluxplant_api.APPLICATION
#WebApp 2 Pointer
- url: /.*
  script: fluxplant.app

#Static Files
- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0